### ISSUE TITLE
Imgix::Rails::UrlHelper

### ISSUE THREAD

**Issue by ravster** [imgix/imgix-rails#12]
We'd like to use the `ix_image_url` in an Oat Serializer, and to do that successfully we have to `include Imgix::Rails::ViewHelper` in the serializer.  That also allows using the tag-helpers in the serializer, which is not something we want.

If we made a PR that created an `Imgix::Rails::UrlHelper` that is fit for use in a serializer, would it be accepted into this gem?  We would set it up so that the existing `ViewHelper` would call the new `UrlHelper` as a dependency.

**Comment by kellysutton** [comment]
Hi @ravster,

Thanks for opening the issue in this regard. Feel free to open the Pull Request and we can discuss that there.

Since you're just dealing with string values, it may be best to just use the [imgix-rb](https://github.com/imgix/imgix-rb) gem (which is a dependency of imgix-rails). Let me know what you think!
