### ISSUE TITLE
Digest hash

### ISSUE THREAD

**Issue by makotot** [imgix/imgix-rails#86]
Is there a way to add a digest hash with imgix-rails same as `image_tag` converts `image_tag("image.jpg")` to such as `image-088ed3d6c28095c7dfecc21d1a70309e.jpg`?

**Comment by sherwinski** [comment]
Hi @makotot 
I believe this is not possible because imgix does not detect when an image's contents have changed, which is necessary to know when generating a new digest hash. If the main concern is keeping your cache up-to-date when a new image is saved over a file, I would recommend looking into incorporating [purge requests](https://docs.imgix.com/setup/purging-images) as part of the image asset pipeline. Please let me know if this solution works for you, thanks!

**Comment by makotot** [comment]
@sherwinski Thanks :) It makes sense. If I solve keeping cache up-to-date with your suggestion, I will comment here.

**Comment by sherwinski** [comment]
Hi @makotot 👋

I was looking through old issues in this repo and noticed #36. It seems that this user is mentioning a similar use case to what you described:

>  So I was getting 404's until I wrapped the paths in image_path before passing them off to ix_image_tag. 

 Would it be possible to generate a digest by passing the path through `image_path` before passing it into `ix_image_path`? This issue is quite old so I am not sure if this suggestion still applies. Curious to hear what you think, thanks.
