### ISSUE TITLE
Getting static image instead of GIF

### ISSUE THREAD

**Issue by designcrumble** [imgix/imgix-rails#92]
Hi there, 
This issue isn't an emergency so considering the current COVID situation, please take your time to respond. 

I am facing problem rendering GIF image, it works perfectly without any params as linked below. 

original GIF — https://sideway.imgix.net/projects/covers/000/000/043/original/wp2757874.gif

GIF with params doesn't work — https://sideway.imgix.net/projects/covers/000/000/043/original/wp2757874.gif?ixlib=rails-
4.0.0&fit=crop&w=1024&dpr=2&q=50

code: 
`=ix_image_tag(@project.cover.path, url_params: { auto: 'format', fit: 'crop', w: 1024})`

**Comment by frederickfogerty** [comment]
Hey @designcrumble! 👋 Luckily we're fully operational from home so we can help you out here! Thanks for reaching out to us. 

I understand the confusion here. To explain a little bit, without any image parameters, imgix acts as a proxy, and just passes anything you load straight through to you, without any transformations. Then, only when you add image parameters will imgix actually do anything with your image/GIF/whatever file you pass through. 

In this case, the reason why the GIF with params doesn’t work is because for us to process GIFs, we require the account to have our animated GIF features, which usually requires the account to be a Premium account.

If this is something you're interested in, our sales team would be more than happy to discuss this and see if there’s something we can work out for you here. You can reach out to them at sales@imgix.com, or if you’d like, I can request them to reach out to you directly. Let me know what you’d like!

**Comment by frederickfogerty** [comment]
I'm going to close this now, but please still comment if you'd like to discuss this further or you think we haven't sufficiently answered this question.

**Comment by designcrumble** [comment]
Hey, 
Thanks for your quick response! 
Can I find the pricing plans for Premium somewhere? If it's not public then I can reach out to them. 

Thanks for your help!

**Comment by frederickfogerty** [comment]
No worries at all! Unfortunately these plans are not public and you'll have to reach out to the sales team. Thanks again ☺️
